apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-registry-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.16.28
    path: /nfs/registry
