apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-registry-pvc
spec:
  storageClassName: nfs-storageclass
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
