apiVersion: v1
kind: Service
metadata:
  name: priv-registry-web-ui-svc
spec:
  selector:
    app: priv-registry-web-ui
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  type: NodePort
