apiVersion: v1
kind: Service
metadata:
  name: fastapi-test-svc
  namespace: test
spec:
  type: NodePort
  selector:
    app: fastapi-test
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 31800
