apiVersion: v1
kind: Service
metadata:
  name: fastapi-production-svc
  namespace: product
spec:
  type: NodePort
  selector:
    app: fastapi-production
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30800
